### ISSUE TITLE
Allow extnding of inventory

### ISSUE THREAD

**Issue by zeezabug** [Vagabottos/root-rpg#91] opened 2022-07-25 07:51 UTC
Allow extension of the inventory so you can see details of the items, similar to the plus buttons on the abilities tab. 

<img width="725" alt="Screen Shot 2022-07-25 at 7 51 08 PM" src="https://user-images.githubusercontent.com/109948278/180726110-07ce64e7-cd3a-4d63-ac73-0df67f5ea15f.png">

**Comment by seiyria** [comment] 2022-07-25 11:53
This is a known bug.

**Comment by seiyria** [comment] 2023-01-05 19:02
duplicate of #90

**Closed by seiyria** 2023-01-05 19:02 UTC
Labels: bug
